# Generated by Django 3.2.3 on 2021-07-10 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 10, 17, 6, 17, 272678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 10, 17, 6, 17, 274678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 10, 17, 6, 17, 272678, tzinfo=utc)),
        ),
    ]
